# Generated by Django 3.2.25 on 2025-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text="Path under static/, e.g. 'images/products/cedarwood-glow.jpg'", max_length=255),
        ),
    ]
